[[constraint]]
  name = "github.com/buaazp/fasthttprouter"
  version = "0.1.1"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20180529.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
